version: '3'

services:
  postgresql:
    image: postgres
    container_name: lesson
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=lesson
    command: postgres
    restart: always